### ISSUE TITLE
Toda la idea de etcd es que reduce la configuración

### ISSUE THREAD

**Issue by JJ** [PedroMFC/EvaluaUGR#85]
Si tienes que poner a mano los puertos del cluster, es un error grande. Pueden estar en otro host, pueden usar otros puertos, pueden ser menos y no 3.

**Comment by PedroMFC** [comment]
Intenté seguir la estructura vista en clase pero es cierto que si está la opción de poner un puerto a mano puede acarrear problemas. Eliminaré esa posibilidad.
